#!/bin/sh

check_emails() {
  recipient="$1"
  unread=$(notmuch count tag:new to:"${recipient}")

  if [ "${unread}" -gt 0 ]; then
    notify-send "${recipient}" "${unread} unread email(s)"
  fi

  notmuch tag +inbox +unread -new -- tag:new
}

check_emails "${EMAIL}"
check_emails "public@tomaskala.com"
