#!/bin/sh

tag_emails() {
  address="$1"
  unread=$(notmuch count tag:new to:"${address}")

  if [ "${unread}" -gt 0 ]; then
    notify-send "${address}" "${unread} unread email(s)"
  fi

  notmuch tag +inbox +unread -new -- tag:new
  notmuch tag +sent -inbox -unread -new -- from:"${address}"
}

tag_emails "${EMAIL}"
tag_emails "public@tomaskala.com"
